version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/development.Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 3030:3030
    volumes:
      - ./:/opt/api:delegated
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=mongo:27017
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOSTS_TIMEOUT=50
      - YAYHOORAY_API_PORT=3030
      - YAYHOORAY_MONGODB_URL=mongodb://yay:hooray@mongo:27017/yayhooray
      - YAYHOORAY_JWT_SECRET=dontUseThisSecretInProduction
      - YAYHOORAY_MAX_URLNAME_ATTEMPTS=10
      - YAYHOORAY_ALLOWED_CATEGORIES=Advice,Discussions,Meaningless,Projects
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.3
    restart: unless-stopped
    logging:
      driver: "none"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=yayhooray
      - MONGO_INITDB_ROOT_USERNAME=yay
      - MONGO_INITDB_ROOT_PASSWORD=hooray
    volumes:
      - ./docker/mongo/tmp:/data/db
      - ./docker/mongo/init.sh:/docker-entrypoint-initdb.d/init.sh

networks:
  default:
